import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { FrontPagePortfolioGrid } from "../components/FrontPagePortfolioGrid";
import { Sidebar } from "../components/Sidebar";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen bg-cream">
        <Sidebar />
        <FrontPagePortfolioGrid />
      </main>
    </>
  );
};

export default Home;
