import { type NextPage } from "next";
import Head from "next/head";
import { FrontPagePortfolioGrid } from "../components/FrontPagePortfolioGrid";
import { Sidebar } from "../components/Sidebar";
import type { PortfolioEntry } from "../types/sanity";
import { sanityClient } from "../utils/sanity";

interface HomeProps {
  portfolioEntries: PortfolioEntry[];
}

const Home: NextPage<HomeProps> = ({ portfolioEntries }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-8 bg-cream p-8 sm:box-border sm:w-full lg:flex-row">
        <Sidebar />
        <FrontPagePortfolioGrid portfolioEntries={portfolioEntries} />
      </main>
    </>
  );
};

export async function getStaticProps() {
  const portfolioEntries = await sanityClient.fetch(
    `*[_type == 'portfolioEntry']{
      name,
      "imageUrl": image.asset->url 
    }`
  );

  return {
    props: {
      portfolioEntries,
    },
  };
}

export default Home;
